environment: development
name: ffc-grants-addvalue-web
namespace: ffc-grants
workstream: ffc-grants
image: ffc-grants-addvalue-web

labels: {}

appInsights:
  key: not-a-real-key

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
  
containerConfigMap:
  name: ffc-grants-addvalue-web-config-map

containerSecret:
  name: ffc-grants-addvalue-web-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: high
  minReadySeconds: 2
  redeployOnChange: update this field to force a change
  replicas: 2
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  readOnlyRootFilesystem: true
  redisHostname: redis
  redisPassword: redis
  cookiePassword: thisisnotarealpasswordthisisnotarealpassword
  redisPort: 6379
  redisPartition: ffc-grants-addvalue-web
  sessionCacheTTL: 1200000
  messageQueueHost: dummy
  projectDetailsQueueAddress: project-details
  contactDetailsQueueAddress: contact-details
  loginRequired: false
  authUsername: grants
  authPasswordHash: dummy
  backendPollingHost: http://ffc-grants-addval-eligibility
  pollingInterval: 200
  pollingRetries: 20
  protectiveMonitoringUrl:
  googleTagManagerKey: dummy
  googleTagManagerServerKey: dummy
  startPageUrl: dummy
  serviceEndDate: dummy
  serviceEndTime: dummy
  surveyLink: dummy

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

service:
  port: 80

ingress:
  class: nginx
  endpoint: ffc-grants-frontend
  server: example.com
  path: /adding-value
