{{- include "ffc-helm-library.container-config-map" (list . "ffc-grants-addvalue-web.config-map") -}}
{{- define "ffc-grants-addvalue-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}  
  REDIS_HOSTNAME: {{ .Values.container.redisHostname | quote }}
  REDIS_PORT: {{ .Values.container.redisPort | quote }}
  REDIS_PARTITION: {{ .Values.container.redisPartition | quote }}
  SESSION_CACHE_TTL: {{ .Values.container.sessionCacheTTL | quote }}  
  LOGIN_REQUIRED: {{ .Values.container.loginRequired | quote }}
  SERVICE_BUS_HOST: {{ .Values.container.messageQueueHost | quote }}
  PROJECT_DETAILS_QUEUE_ADDRESS: {{ .Values.container.projectDetailsQueueAddress | quote }}
  CONTACT_DETAILS_QUEUE_ADDRESS: {{ .Values.container.contactDetailsQueueAddress | quote }}
  BACKEND_POLLING_HOST: {{ .Values.container.backendPollingHost | quote }}
  POLLING_INTERVAL: {{ .Values.container.pollingInterval | quote }}
  POLLING_RETRIES: {{ .Values.container.pollingRetries | quote }}
  APPINSIGHTS_CLOUDROLE: {{ .Values.name }}
  GOOGLE_TAG_MANAGER_KEY: {{ .Values.container.googleTagManagerKey | quote }}
  GOOGLE_TAG_MANAGER_SERVER_KEY: {{ .Values.container.googleTagManagerServerKey | quote }}
  START_PAGE_URL: {{ .Values.container.startPageUrl | quote }}
  SERVICE_END_DATE : {{ .Values.container.serviceEndDate | quote }}
  SERVICE_END_TIME : {{ .Values.container.serviceEndTime | quote }}
  SURVEY_LINK: {{ .Values.container.surveyLink | quote }}
{{- end -}}
